# Generated by Django 4.0.4 on 2022-05-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangalorejobs',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bangalorejobs',
            name='eligibility',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bangalorejobs',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mumbaijobs',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mumbaijobs',
            name='eligibility',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mumbaijobs',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
